sudo: required

language: php
php:
    - 5.6
    - 7.0
    - 7.1

services:
    - mysql

env:
    global:
        - DB_HOST=127.0.0.1
        - DB_USER=travis
        - DB_PASS=""
        - DB_NAME=membership

before_install:
    - mysql -e 'CREATE DATABASE $DB_NAME;'
    - composer self-update

install:
    - composer install

before_script:
    - cp app/settings.php.disable app/settings.php

script:
    - vendor/bin/codecept run
