language: php
php:
    - 5.6
    - 7.0
    - 7.1

services:
    - mysql

env:
    global:
        - DB_HOST=127.0.0.1
        - DB_USER=travis
        - DB_PASS=""
        - DB_NAME=membership

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - composer self-update

install:
    - composer install

before_script:
    - mysql -e 'CREATE DATABASE membership;'
    - cp app/settings.php.disable app/settings.php

script:
    - vendor/bin/codecept run --coverage
